#!/sbin/busybox sh

# $1 - "adb_mode"
# $2 - value=

if [ "a$2" == "a" ]; then
	echo "$adb_mode";
else
	adb_mode=$2;
	echo "$adb_mode";
fi;

case "${adb_mode}" in
	0)
		# tmp is cleaned on boot before this check.
		if [ -e /tmp/adbd.bkp ]; then
			stop adbd;
			mv /tmp/adbd.bkp /sbin/adbd;
			chmod 755 /sbin/adbd;
			start adbd;
		fi;
	;;
	1)
		if [ ! -e /tmp/adbd.bkp ]; then
			cp -a /sbin/adbd /tmp/adbd.bkp
		fi;
		stop adbd;
		xzcat /sbin/adbd.jb.xz > /sbin/adbd;
		chmod 755 /sbin/adbd;
		start adbd;
	;;
	*)
		adb_mode=0;
	;;
esac;

