#!/sbin/busybox sh

# $1 - "add_remove_root"
# $2 - value=

if [ "a$2" == "a" ]; then
        echo $add_remove_root
else
        add_remove_root=$2
        echo $add_remove_root
fi;

case "${add_remove_root}" in
	Nothing)

		;;
	Removed)
	if [ -f /system/xbin/su ]; then
		mount -o remount,rw /dev/block/mmcblk0p9 /system > /dev/null 2>&1
		rm -f /system/bin/su > /dev/null 2>&1
		rm -f /system/xbin/su > /dev/null 2>&1
		# some roms have a busybox with su applet
		rm -f /system/xbin/busybox > /dev/null 2>&1
		ln -s /sbin/busybox /system/xbin/busybox > /dev/null 2>&1
		# I need to remove this as well for Garanti CepBank app
		mv /system/xbin/which /system/xbin/waswhich-bkp > /dev/null 2>&1
		rm -f /system/xbin/which > /dev/null 2>&1
		# 1SuperUser, superuser Superuser SuperUser whatever...
		rm -rf /data/dalvik-cache/*uper?ser.apk* > /dev/null 2>&1
		rm -f /system/app/*uper?ser.apk > /dev/null 2>&1
		rm -f /data/app/*uper?ser.apk > /dev/null 2>&1
		mount -o remount,ro /dev/block/mmcblk0p9 /system > /dev/null 2>&1
		# run reinstall-helper
		#/sbin/busybox sh /sbin/ext/su-helper.sh
	fi;
		;;
	Restored)
	if [ ! -f /system/xbin/su ]; then
		mount -o remount,rw /dev/block/mmcblk0p9 /system > /dev/null 2>&1
                /sbin/busybox sh /sbin/ext/install.sh > /dev/null 2>&1
                # Restore witch if exist
                if [ -e /system/xbin/waswhich-bkp ]; then
                	cp /system/xbin/waswhich-bkp /system/xbin/which
                fi;
	fi;
		;;
	*)
		add_remove_root=Nothing
		;;
esac;

