#!/sbin/busybox sh

# $1 - "awake_booster_delay"
# $2 - value=

if [ "a$2" == "a" ]; then
	echo $awake_booster_delay
else
	awake_booster_delay=$2
	echo $awake_booster_delay
fi;

if [ "a$awake_booster_delay" == "a" ]; then
        awake_booster_delay=3
fi;
