#!/sbin/busybox sh

# $1 - "awake_booster"
# $2 - value=

if [ "a$2" == "a" ]; then
	echo $awake_booster
else
	awake_booster=$2
	echo $awake_booster
fi;

if [ "a$awake_booster" == "a" ]; then
	awake_booster=1
fi;

