#!/sbin/busybox sh

# $1 - "bln_reset_notification"
# $2 - value=

PROFILE=$(cat /data/.siyah/.active.profile);
. /data/.siyah/$PROFILE.profile;

if [ "a$2" != "a" ]; then
        bln_reset_notification=$2
fi;

case "${bln_reset_notification}" in
	0)
		echo "$notification_timeout $bln_charging_notification 1" > /sys/class/misc/backlightnotification/notification_timeout
	;;
	1)
                echo "$notification_timeout $bln_charging_notification 0" > /sys/class/misc/backlightnotification/notification_timeout
	;;
	*)
	bln_reset_notification=0
	;;
esac;

echo ${bln_reset_notification}

