#!/sbin/busybox sh

if [ "a$3" == "a" ]; then
	evalcmd='eval "echo \$chargecurrent$2"';
	eval $evalcmd;
else
	evalcmd='eval "chargecurrent$2=$3"';
	eval $evalcmd;
	evalcmd='eval "echo \$chargecurrent$2"';
	eval $evalcmd;
fi;

echo "$chargecurrent1" "$chargecurrent2" "$chargecurrent3" > /sys/devices/virtual/misc/charge_current/charge_current;

