#!/sbin/busybox sh

# $1 - "cortexbrain_background_process"
# $2 - value=

if [ "a$2" == "a" ]; then
	echo $cortexbrain_background_process
else
	cortexbrain_background_process=$2
	echo $cortexbrain_background_process
fi;

PIDOFCORTEX=`pgrep -f "/sbin/busybox sh /sbin/ext/cortexbrain-tune.sh"`;

case "${cortexbrain_background_process}" in
	0)
		if [ "a$PIDOFCORTEX" != "a" ]; then
			kill ${PIDOFCORTEX};
		fi;
		;;
	1)
		if [ "a$PIDOFCORTEX" == "a" ]; then
			/sbin/ext/cortexbrain-tune.sh $cortexbrain_background_process;
		fi;
		;;
	*)
		cortexbrain_background_process=0
		;;
esac;

