#!/sbin/busybox sh

# $1 - "cortexbrain_memory"
# $2 - value=

if [ "a$2" == "a" ]; then
	echo $cortexbrain_memory
else
	cortexbrain_memory=$2
	echo $cortexbrain_memory
fi;

if [ "a$cortexbrain_memory" == "a" ]; then
	cortexbrain_memory=1
fi;

