#!/sbin/busybox sh

# $1 - "cortexbrain_cpu"
# $2 - value=

if [ "a$2" == "a" ]; then
	echo $cortexbrain_cpu
else
	cortexbrain_cpu=$2
	echo $cortexbrain_cpu
fi;

if [ "a$cortexbrain_cpu" == "a" ]; then
	cortexbrain_cpu=1
fi;

