#!/sbin/busybox sh

# $1 - "cortexbrain_battery"
# $2 - value=

if [ "a$2" == "a" ]; then
	echo $cortexbrain_battery
else
	cortexbrain_battery=$2
	echo $cortexbrain_battery
fi;

if [ "a$cortexbrain_battery" == "a" ]; then
	cortexbrain_battery=1
fi;

