#!/sbin/busybox sh

# $1 - "cortexbrain_background_process"
# $2 - value=

if [ "a$2" == "a" ]; then
	echo $cortexbrain_background_process
else
	cortexbrain_background_process=$2
	echo $cortexbrain_background_process
fi;

case "${cortexbrain_background_process}" in
	0)
		PIDOFCORTEX=`pgrep -f "/sbin/busybox sh /sbin/ext/cortexbrain-tune.sh"`;
		kill ${PIDOFCORTEX} > /dev/null 2>&1;
		;;
	1)
		PIDOFCORTEX=`pgrep -f "/sbin/busybox sh /sbin/ext/cortexbrain-tune.sh"`;
		if [ "a$PIDOFCORTEX" == "a" ]; then
			/sbin/busybox sh /sbin/ext/cortexbrain-tune.sh 1 > /dev/null 2>&1;
		fi;
		;;
	*)
		cortexbrain_background_process=1
		;;
esac;

