#!/sbin/busybox sh

# $1 - "cortexbrain_auto_tweak_brightness"
# $2 - value=

if [ "a$2" == "a" ]; then
	echo $cortexbrain_auto_tweak_brightness
else
	cortexbrain_auto_tweak_brightness=$2
	echo $cortexbrain_auto_tweak_brightness
fi;

