#!/sbin/busybox sh

PROFILE=`cat /data/.siyah/.active.profile`;
. /data/.siyah/$PROFILE.profile;

if [ "a$3" == "a" ]; then
	evalcmd='eval "echo \$CPUVOLT$2"';
	eval $evalcmd;
else
	evalcmd='eval "CPUVOLT$2=$3"';
	eval $evalcmd;
	evalcmd='eval "echo \$CPUVOLT$2"';
	eval $evalcmd;

	if [ "$cpu_voltage_switch" == on ]; then
		echo "100000 $CPUVOLT23" > /sys/devices/system/cpu/cpu0/cpufreq/vdd_levels;
		echo "150000 $CPUVOLT22" > /sys/devices/system/cpu/cpu0/cpufreq/vdd_levels;
		echo "200000 $CPUVOLT21" > /sys/devices/system/cpu/cpu0/cpufreq/vdd_levels;
		echo "250000 $CPUVOLT20" > /sys/devices/system/cpu/cpu0/cpufreq/vdd_levels;
		echo "300000 $CPUVOLT19" > /sys/devices/system/cpu/cpu0/cpufreq/vdd_levels;
		echo "350000 $CPUVOLT18" > /sys/devices/system/cpu/cpu0/cpufreq/vdd_levels;
		echo "400000 $CPUVOLT17" > /sys/devices/system/cpu/cpu0/cpufreq/vdd_levels;
		echo "450000 $CPUVOLT16" > /sys/devices/system/cpu/cpu0/cpufreq/vdd_levels;
		echo "500000 $CPUVOLT15" > /sys/devices/system/cpu/cpu0/cpufreq/vdd_levels;
		echo "550000 $CPUVOLT14" > /sys/devices/system/cpu/cpu0/cpufreq/vdd_levels;
		echo "600000 $CPUVOLT13" > /sys/devices/system/cpu/cpu0/cpufreq/vdd_levels;
		echo "650000 $CPUVOLT12" > /sys/devices/system/cpu/cpu0/cpufreq/vdd_levels;
		echo "700000 $CPUVOLT11" > /sys/devices/system/cpu/cpu0/cpufreq/vdd_levels;
		echo "750000 $CPUVOLT10" > /sys/devices/system/cpu/cpu0/cpufreq/vdd_levels;
		echo "800000 $CPUVOLT9" > /sys/devices/system/cpu/cpu0/cpufreq/vdd_levels;
		echo "850000 $CPUVOLT8" > /sys/devices/system/cpu/cpu0/cpufreq/vdd_levels;
		echo "900000 $CPUVOLT7" > /sys/devices/system/cpu/cpu0/cpufreq/vdd_levels;
		echo "950000 $CPUVOLT6" > /sys/devices/system/cpu/cpu0/cpufreq/vdd_levels;
		echo "1000000 $CPUVOLT5" > /sys/devices/system/cpu/cpu0/cpufreq/vdd_levels;
		echo "1050000 $CPUVOLT4" > /sys/devices/system/cpu/cpu0/cpufreq/vdd_levels;
		echo "1100000 $CPUVOLT3" > /sys/devices/system/cpu/cpu0/cpufreq/vdd_levels;
		echo "1150000 $CPUVOLT2" > /sys/devices/system/cpu/cpu0/cpufreq/vdd_levels;
		echo "1200000 $CPUVOLT1" > /sys/devices/system/cpu/cpu0/cpufreq/vdd_levels;
		echo "1300000 1350" > /sys/devices/system/cpu/cpu0/cpufreq/vdd_levels;
		echo "1400000 1375" > /sys/devices/system/cpu/cpu0/cpufreq/vdd_levels;
		echo "1500000 1400" > /sys/devices/system/cpu/cpu0/cpufreq/vdd_levels;
		echo "1600000 1450" > /sys/devices/system/cpu/cpu0/cpufreq/vdd_levels;
	fi;
fi;
