#!/sbin/busybox sh

if [ "a$2" != "a" ]; then
	echo $2 > $EXTERNAL_STORAGE/.defaultrom
fi;

if [ -f $EXTERNAL_STORAGE/.defaultrom ]; then
	if [ `cat $EXTERNAL_STORAGE/.defaultrom` -eq "1" ]; then
		echo "1"
	else
		echo "0"
	fi;
fi;
