#!/sbin/busybox sh
# 1 - "generic_mod1"
# 2 - symbol name
# 3 - type
# 4 - value

configname=$2$3

if [ "a$4" == "a" ]; then
	evalcmd='eval "echo \$$configname"'
	eval $evalcmd
else
	evalcmd='eval "$configname=$4"'
	eval $evalcmd
	evalcmd='eval "echo \$$configname"'
	eval $evalcmd
	kmemhelper -n $2 -t $3 $4 > /dev/null 2>&1
fi


