#!/sbin/busybox sh

if [ "a$2" == "a" ]; then
	exit
fi

filename=$(basename $2)

if [ "a$3" == "a" ]; then
	evalcmd='eval "echo \$$filename"'
	eval $evalcmd
else
	evalcmd='eval "$filename=$3"'
	eval $evalcmd
	evalcmd='eval "echo \$$filename"'
	eval $evalcmd
	if [ -f $2 ];then
		case "$3" in
			off)
				echo 0 > $2
			;;
			on)
				LED_TIMEOUT_SET=`cat /sys/class/misc/backlightnotification/led_timeout`
				echo "$LED_TIMEOUT_SET" > $2
			;;
		esac;
	fi;
fi;

