#!/sbin/busybox sh

if [ "a$2" != "a" ]; then

	filename=$(basename $2);

	if [ "a$3" == "a" ]; then
		evalcmd='eval "echo \$$filename"';
		eval $evalcmd;
	else
		newfreq=$3;
		if [ "$newfreq" == "850000" ] || [ "$newfreq" == "950000" ]; then
			newfreq=$(($newfreq + 2000));
		fi;

		evalcmd='eval "$filename=$newfreq"';
		eval $evalcmd;
		evalcmd='eval "echo \$$filename"';
		eval $evalcmd;
	fi;
fi;

