#!/sbin/busybox sh

if [ "a$2" == "a" ]; then
	exit;
fi

filename=$(basename $2);

if [ "a$3" == "a" ]; then
	evalcmd='eval "echo \$$filename"';
	eval $evalcmd;
else
	evalcmd='eval "$filename=$3"';
	eval $evalcmd;
	evalcmd='eval "echo \$$filename"';
	eval $evalcmd;
	if [ -f $2 ]; then
		case "$3" in
			off)
				pkill -f "gesture_set.sh";
				pkill -f "/sys/devices/virtual/misc/touch_gestures/wait_for_gesture";
				echo "0" > /sys/devices/virtual/sec/sec_touchscreen/tsp_gestures;
			;;
			on)
				echo "1" > /sys/devices/virtual/sec/sec_touchscreen/tsp_gestures;
				pkill -f "gesture_set.sh";
				pkill -f "/sys/devices/virtual/misc/touch_gestures/wait_for_gesture";
				/sbin/busybox sh /data/gesture_set.sh;
			;;
		esac;
	fi;
fi;

