#!/sbin/busybox sh

if [ "a$2" != "a" ]; then

	mount -o remount,rw /

	filename=$(basename $2);

	if [ "a$3" == "a" ]; then
		evalcmd='eval "echo \$$filename"';
		eval $evalcmd;
	else
		evalcmd='eval "$filename=$3"';
		eval $evalcmd;
		evalcmd='eval "echo \$$filename"';
		eval $evalcmd;
	fi;

	case "$3" in
		off)
			echo 0 > /sys/kernel/mm/ksm/run;
			echo 2 > /sys/kernel/mm/ksm/run;
			echo "off" > /tmp/ksm;
		;;
		on)
			if [ `cat /tmp/ksm` == "off" ]; then
				/sbin/ext/cortexbrain-tune.sh;
				echo "on" > /tmp/ksm;
			fi;
		;;
	esac;
fi;

