#!/sbin/busybox sh

if [ "a$2" != "a" ]; then

	mount -o remount,rw /

	filename=$(basename $2);

	if [ "a$3" == "a" ]; then
		evalcmd='eval "echo \$$filename"';
		eval $evalcmd;
	else
		evalcmd='eval "$filename=$3"';
		eval $evalcmd;
		evalcmd='eval "echo \$$filename"';
		eval $evalcmd;
	fi;

	case "$3" in
		off)
			echo 0 > /sys/kernel/mm/ksm/run;
			echo 2 > /sys/kernel/mm/ksm/run;
			echo "0" > /tmp/ksm;
		;;
		on)
			KSM_STATUS=`cat /tmp/ksm`;
			if [ "$KSM_STATUS" == "0" ]; then
				/sbin/ext/cortexbrain-tune.sh;
				echo "1" > /tmp/ksm;
			fi;
		;;
	esac;
fi;

