#!/sbin/busybox sh

# $1 - "gpsregion"
# $2 - value=

/sbin/busybox mount -o remount,rw /system

# Backup original gps.conf in case of user revert by using 7 case.
if [ ! -e /system/etc/gps.conf.bkp ]; then
	cp -a /system/etc/gps.conf /system/etc/gps.conf.bkp
fi;

if [ "a$2" == "a" ]; then
	echo $gpsregion
else
        gpsregion=$2
	echo $gpsregion
fi;

case "${gpsregion}" in
	No_GPS_Zone_changes)

	;;
Asia)
	CHECKGPS=`cat /system/etc/gps.conf | grep NTP_SERVER=0.asia.pool.ntp.org`
	if [ "$CHECKGPS" != "NTP_SERVER=0.asia.pool.ntp.org" ]; then
		sed -i "s/NTP_SERVER[.a-zA-Z\=-\0-5\]*//g" /system/etc/gps.conf
		sed -i "s/-america[.a-zA-Z\=-\0-5\]*//g" /system/etc/gps.conf
		echo "NTP_SERVER=asia.pool.ntp.org" >> /system/etc/gps.conf
		echo "NTP_SERVER=0.asia.pool.ntp.org" >> /system/etc/gps.conf
		echo "NTP_SERVER=1.asia.pool.ntp.org" >> /system/etc/gps.conf
		echo "NTP_SERVER=2.asia.pool.ntp.org" >> /system/etc/gps.conf
		echo "NTP_SERVER=3.asia.pool.ntp.org" >> /system/etc/gps.conf
	fi;
	;;
Europe)
	CHECKGPS=`cat /system/etc/gps.conf | grep NTP_SERVER=0.europe.pool.ntp.org`
	if [ "$CHECKGPS" != "NTP_SERVER=0.europe.pool.ntp.org" ]; then
		sed -i "s/NTP_SERVER[.a-zA-Z\=-\0-5\]*//g" /system/etc/gps.conf
		sed -i "s/-america[.a-zA-Z\=-\0-5\]*//g" /system/etc/gps.conf
                echo "NTP_SERVER=europe.pool.ntp.org" >> /system/etc/gps.conf
                echo "NTP_SERVER=0.europe.pool.ntp.org" >> /system/etc/gps.conf
                echo "NTP_SERVER=1.europe.pool.ntp.org" >> /system/etc/gps.conf
                echo "NTP_SERVER=2.europe.pool.ntp.org" >> /system/etc/gps.conf
                echo "NTP_SERVER=3.europe.pool.ntp.org" >> /system/etc/gps.conf
	fi;
	;;
Oceania)
        CHECKGPS=`cat /system/etc/gps.conf | grep NTP_SERVER=0.oceania.pool.ntp.org`
        if [ "$CHECKGPS" != "NTP_SERVER=0.oceania.pool.ntp.org" ]; then
                sed -i "s/NTP_SERVER[.a-zA-Z\=-\0-5\]*//g" /system/etc/gps.conf
		sed -i "s/-america[.a-zA-Z\=-\0-5\]*//g" /system/etc/gps.conf
                echo "NTP_SERVER=oceania.pool.ntp.org" >> /system/etc/gps.conf
                echo "NTP_SERVER=0.oceania.pool.ntp.org" >> /system/etc/gps.conf
                echo "NTP_SERVER=1.oceania.pool.ntp.org" >> /system/etc/gps.conf
                echo "NTP_SERVER=2.oceania.pool.ntp.org" >> /system/etc/gps.conf
                echo "NTP_SERVER=3.oceania.pool.ntp.org" >> /system/etc/gps.conf
        fi;
	;;
North-America)
        CHECKGPS=`cat /system/etc/gps.conf | grep NTP_SERVER=0.north-america.pool.ntp.org`
        if [ "$CHECKGPS" != "NTP_SERVER=0.north-america.pool.ntp.org" ]; then
                sed -i "s/NTP_SERVER[.a-zA-Z\=-\0-5\]*//g" /system/etc/gps.conf
		sed -i "s/-america[.a-zA-Z\=-\0-5\]*//g" /system/etc/gps.conf
                echo "NTP_SERVER=north-america.pool.ntp.org" >> /system/etc/gps.conf
                echo "NTP_SERVER=0.north-america.pool.ntp.org" >> /system/etc/gps.conf
                echo "NTP_SERVER=1.north-america.pool.ntp.org" >> /system/etc/gps.conf
                echo "NTP_SERVER=2.north-america.pool.ntp.org" >> /system/etc/gps.conf
                echo "NTP_SERVER=3.north-america.pool.ntp.org" >> /system/etc/gps.conf
        fi;
	;;
South-America)
        CHECKGPS=`cat /system/etc/gps.conf | grep NTP_SERVER=0.south-america.pool.ntp.org`
        if [ "$CHECKGPS" != "NTP_SERVER=0.south-america.pool.ntp.org" ]; then
                sed -i "s/NTP_SERVER[.a-zA-Z\=-\0-5\]*//g" /system/etc/gps.conf
		sed -i "s/-america[.a-zA-Z\=-\0-5\]*//g" /system/etc/gps.conf
                echo "NTP_SERVER=south-america.pool.ntp.org" >> /system/etc/gps.conf
                echo "NTP_SERVER=0.south-america.pool.ntp.org" >> /system/etc/gps.conf
                echo "NTP_SERVER=1.south-america.pool.ntp.org" >> /system/etc/gps.conf
                echo "NTP_SERVER=2.south-america.pool.ntp.org" >> /system/etc/gps.conf
                echo "NTP_SERVER=3.south-america.pool.ntp.org" >> /system/etc/gps.conf
        fi;
	;;
Africa)
        CHECKGPS=`cat /system/etc/gps.conf | grep NTP_SERVER=3.africa.pool.ntp.org`
        if [ "$CHECKGPS" != "NTP_SERVER=3.africa.pool.ntp.org" ]; then
                sed -i "s/NTP_SERVER[.a-zA-Z\=-\0-5\]*//g" /system/etc/gps.conf
		sed -i "s/-america[.a-zA-Z\=-\0-5\]*//g" /system/etc/gps.conf
                echo "NTP_SERVER=3.africa.pool.ntp.org" >> /system/etc/gps.conf
                echo "NTP_SERVER=1.pool.ntp.org" >> /system/etc/gps.conf
                echo "NTP_SERVER=3.pool.ntp.org" >> /system/etc/gps.conf
        fi;
	;;
Original_ROM_GPS_Restored)
		cp -a /system/etc/gps.conf.bkp /system/etc/gps.conf
	;;
*)
	gpsregion=No_GPS_Zone_changes
	;;
esac;

