#!/sbin/busybox sh

# $1 - "gpsregion"
# $2 - value=

gpsregion=$2

/sbin/busybox mount -o remount,rw /system

# Backup original gps.conf in case of user revert by using 7 case.
if [ ! -e /system/etc/gps.conf.bkp ]; then
	cp -a /system/etc/gps.conf /system/etc/gps.conf.bkp
fi;

case "${gpsregion}" in
	0)
		echo "No Changes to GPS zone"
		GPSZONE=No_GPS_Zone_changes
	;;
	1)
	CHECKGPS=`cat /system/etc/gps.conf | grep NTP_SERVER=0.asia.pool.ntp.org`
	if [ "$CHECKGPS" == "NTP_SERVER=0.asia.pool.ntp.org" ]; then
		echo "Asia GPS set"
	else
		sed -i "s/NTP_SERVER[.a-zA-Z\=-\0-5\]*//g" /system/etc/gps.conf
		sed -i "s/-america[.a-zA-Z\=-\0-5\]*//g" /system/etc/gps.conf
		echo "NTP_SERVER=asia.pool.ntp.org" >> /system/etc/gps.conf
		echo "NTP_SERVER=0.asia.pool.ntp.org" >> /system/etc/gps.conf
		echo "NTP_SERVER=1.asia.pool.ntp.org" >> /system/etc/gps.conf
		echo "NTP_SERVER=2.asia.pool.ntp.org" >> /system/etc/gps.conf
		echo "NTP_SERVER=3.asia.pool.ntp.org" >> /system/etc/gps.conf
		GPSZONE=Asia
	fi;
	;;
	2)
	CHECKGPS=`cat /system/etc/gps.conf | grep NTP_SERVER=0.europe.pool.ntp.org`
	if [ "$CHECKGPS" == "NTP_SERVER=0.europe.pool.ntp.org" ]; then
		echo "Europe GPS set"
	else
		sed -i "s/NTP_SERVER[.a-zA-Z\=-\0-5\]*//g" /system/etc/gps.conf
		sed -i "s/-america[.a-zA-Z\=-\0-5\]*//g" /system/etc/gps.conf
                echo "NTP_SERVER=europe.pool.ntp.org" >> /system/etc/gps.conf
                echo "NTP_SERVER=0.europe.pool.ntp.org" >> /system/etc/gps.conf
                echo "NTP_SERVER=1.europe.pool.ntp.org" >> /system/etc/gps.conf
                echo "NTP_SERVER=2.europe.pool.ntp.org" >> /system/etc/gps.conf
                echo "NTP_SERVER=3.europe.pool.ntp.org" >> /system/etc/gps.conf
		GPSZONE=Europe
	fi;
	;;
	3)
        CHECKGPS=`cat /system/etc/gps.conf | grep NTP_SERVER=0.oceania.pool.ntp.org`
        if [ "$CHECKGPS" == "NTP_SERVER=0.oceania.pool.ntp.org" ]; then
                echo "Oceania GPS set"
        else
                sed -i "s/NTP_SERVER[.a-zA-Z\=-\0-5\]*//g" /system/etc/gps.conf
		sed -i "s/-america[.a-zA-Z\=-\0-5\]*//g" /system/etc/gps.conf
                echo "NTP_SERVER=oceania.pool.ntp.org" >> /system/etc/gps.conf
                echo "NTP_SERVER=0.oceania.pool.ntp.org" >> /system/etc/gps.conf
                echo "NTP_SERVER=1.oceania.pool.ntp.org" >> /system/etc/gps.conf
                echo "NTP_SERVER=2.oceania.pool.ntp.org" >> /system/etc/gps.conf
                echo "NTP_SERVER=3.oceania.pool.ntp.org" >> /system/etc/gps.conf
		GPSZONE=Oceania
        fi;
	;;
	4)
        CHECKGPS=`cat /system/etc/gps.conf | grep NTP_SERVER=0.north-america.pool.ntp.org`
        if [ "$CHECKGPS" == "NTP_SERVER=0.north-america.pool.ntp.org" ]; then
                echo "North-America GPS set"
        else
                sed -i "s/NTP_SERVER[.a-zA-Z\=-\0-5\]*//g" /system/etc/gps.conf
		sed -i "s/-america[.a-zA-Z\=-\0-5\]*//g" /system/etc/gps.conf
                echo "NTP_SERVER=north-america.pool.ntp.org" >> /system/etc/gps.conf
                echo "NTP_SERVER=0.north-america.pool.ntp.org" >> /system/etc/gps.conf
                echo "NTP_SERVER=1.north-america.pool.ntp.org" >> /system/etc/gps.conf
                echo "NTP_SERVER=2.north-america.pool.ntp.org" >> /system/etc/gps.conf
                echo "NTP_SERVER=3.north-america.pool.ntp.org" >> /system/etc/gps.conf
		GPSZONE=North-America
        fi;
	;;
	5)
        CHECKGPS=`cat /system/etc/gps.conf | grep NTP_SERVER=0.south-america.pool.ntp.org`
        if [ "$CHECKGPS" == "NTP_SERVER=0.south-america.pool.ntp.org" ]; then
                echo "South-America GPS set"
        else
                sed -i "s/NTP_SERVER[.a-zA-Z\=-\0-5\]*//g" /system/etc/gps.conf
		sed -i "s/-america[.a-zA-Z\=-\0-5\]*//g" /system/etc/gps.conf
                echo "NTP_SERVER=south-america.pool.ntp.org" >> /system/etc/gps.conf
                echo "NTP_SERVER=0.south-america.pool.ntp.org" >> /system/etc/gps.conf
                echo "NTP_SERVER=1.south-america.pool.ntp.org" >> /system/etc/gps.conf
                echo "NTP_SERVER=2.south-america.pool.ntp.org" >> /system/etc/gps.conf
                echo "NTP_SERVER=3.south-america.pool.ntp.org" >> /system/etc/gps.conf
		GPSZONE=South-America
        fi;
	;;
	6)
        CHECKGPS=`cat /system/etc/gps.conf | grep NTP_SERVER=3.africa.pool.ntp.org`
        if [ "$CHECKGPS" == "NTP_SERVER=3.africa.pool.ntp.org" ]; then
                echo "Africa GPS set"
        else
                sed -i "s/NTP_SERVER[.a-zA-Z\=-\0-5\]*//g" /system/etc/gps.conf
		sed -i "s/-america[.a-zA-Z\=-\0-5\]*//g" /system/etc/gps.conf
                echo "NTP_SERVER=3.africa.pool.ntp.org" >> /system/etc/gps.conf
                echo "NTP_SERVER=1.pool.ntp.org" >> /system/etc/gps.conf
                echo "NTP_SERVER=3.pool.ntp.org" >> /system/etc/gps.conf
		GPSZONE=Africa
        fi;
	;;
	7)
		cp -a /system/etc/gps.conf.bkp /system/etc/gps.conf
		GPSZONE=Original-ROM-GPS.conf-Restored.
	;;
	*)
	gpsregion=0
	;;
esac;
fi;

echo ${GPSZONE}

