#!/sbin/busybox sh

# $1 - "led_timeout"
# $2 - value=

if [ "a$2" == "a" ]; then
	echo "$led_timeout";
else
	led_timeout=$2;
	echo "$led_timeout";
fi;

var_led_timeout="/sys/class/misc/backlightnotification/led_timeout";
var_flash_timeout="/sys/devices/virtual/sec/sec_touchscreen/tsp_flash_timeout";

case "${led_timeout}" in
	off)
		echo "-2" > $var_led_timeout;
	;;
	1)
		echo "1000" > $var_led_timeout;
	;;
	2)
		echo "2000" > $var_led_timeout;
	;;
	3)
		echo "3000" > $var_led_timeout;
	;;
	5)
		echo "5000" > $var_led_timeout;
	;;
	15)
		echo "15000" > $var_led_timeout;
	;;
	30)
		echo "30000" > $var_led_timeout;
	;;
	on)
		echo "-1" > $var_led_timeout;
	;;
	*)
		led_timeout=3;
	;;
esac;

TOUCH_SCREEN_KEYS=`cat $var_flash_timeout`;

if [ $TOUCH_SCREEN_KEYS != "0" ]; then
	TIMEOUT_SET=`cat $var_led_timeout`;
	if [ $TIMEOUT_SET == "-2" ]; then
		echo "0" > $var_flash_timeout;
	elif [ $TIMEOUT_SET == "-1" ]; then
		echo "nothing to do here, touch led is always active";
	else
		echo "$TIMEOUT_SET" > $var_flash_timeout;
	fi;
fi;

