#!/sbin/busybox sh

# $1 - "oom_config_screen_on"
# $2 - value=

if [ "a$2" != "a" ]; then
	oom_config_screen_on=$2;

	case "${oom_config_screen_on}" in
		light)
			echo "1024,2048,2560,4096,6144,8192" > /sys/module/lowmemorykiller/parameters/minfree;
			echo "64" > /sys/module/lowmemorykiller/parameters/cost;
			echo "4096" > /proc/sys/vm/mmap_min_addr;
		;;
		low)
			echo "1024,2048,4096,8192,11776,14848" > /sys/module/lowmemorykiller/parameters/minfree;
			echo "32" > /sys/module/lowmemorykiller/parameters/cost;
			echo "8192" > /proc/sys/vm/mmap_min_addr;
		;;
		medium)
			echo "2560,4096,5632,10240,12288,16384" > /sys/module/lowmemorykiller/parameters/minfree;
			echo "32" > /sys/module/lowmemorykiller/parameters/cost;
			echo "10240" > /proc/sys/vm/mmap_min_addr;
		;;
		default)
			echo "8192,10240,12288,14336,16384,20480" > /sys/module/lowmemorykiller/parameters/minfree;
			echo "32" > /sys/module/lowmemorykiller/parameters/cost;
			echo "14336" > /proc/sys/vm/mmap_min_addr;
		;;
		aggressive)
			echo "8192,10240,12288,16384,24576,32768" > /sys/module/lowmemorykiller/parameters/minfree;
			echo "16" > /sys/module/lowmemorykiller/parameters/cost;
			echo "16384" > /proc/sys/vm/mmap_min_addr;
		;;
		exterminate)
			echo "8192,10240,16384,32768,49152,65536" > /sys/module/lowmemorykiller/parameters/minfree;
			echo "8" > /sys/module/lowmemorykiller/parameters/cost;
			echo "32768" > /proc/sys/vm/mmap_min_addr;
		;;
		*)
			oom_config_screen_on=medium;
		;;
	esac;
fi;

echo ${oom_config_screen_on};

