#!/sbin/busybox sh

# $1 - "oom_config_screen_off"
# $2 - value=

if [ "a$2" != "a" ]; then
	oom_config_screen_off=$2;

	case "${oom_config_screen_off}" in
		light)
			echo "2048,2048,2560,2560,3072,6000" > /sys/module/lowmemorykiller/parameters/minfree;
			echo "64" > /sys/module/lowmemorykiller/parameters/cost;
		;;
		low)
			echo "2048,2560,2560,2560,3584,6000" > /sys/module/lowmemorykiller/parameters/minfree;
			echo "32" > /sys/module/lowmemorykiller/parameters/cost;
		;;
		medium)
			echo "2048,2560,2560,3072,3584,6000" > /sys/module/lowmemorykiller/parameters/minfree;
			echo "32" > /sys/module/lowmemorykiller/parameters/cost;
		;;
		default)
			echo "2048,2560,3072,3584,6000,8192" > /sys/module/lowmemorykiller/parameters/minfree;
			echo "32" > /sys/module/lowmemorykiller/parameters/cost;
		;;
		aggressive)
			echo "2048,2560,3584,6000,8192,12288" > /sys/module/lowmemorykiller/parameters/minfree;
			echo "16" > /sys/module/lowmemorykiller/parameters/cost;
		;;
		exterminate)
			echo "3072,3584,6000,8192,12288,16368" > /sys/module/lowmemorykiller/parameters/minfree;
			echo "8" > /sys/module/lowmemorykiller/parameters/cost;
		;;
		*)
			oom_config_screen_off=medium;
		;;
	esac;
fi;

echo ${oom_config_screen_off};

