#!/sbin/busybox sh

# $1 - "oom_config_screen_off"
# $2 - value=

if [ "a$2" != "a" ]; then
	oom_config_screen_off=$2;

	case "${oom_config_screen_off}" in
		very_light)
			echo "512,1024,1280,2048,3072,4096" > /sys/module/lowmemorykiller/parameters/minfree_screen_off;
			echo "128" > /sys/module/lowmemorykiller/parameters/cost;
			echo "4096" > /proc/sys/vm/mmap_min_addr;
		;;
		light)
			echo "1024,2048,2560,4096,6144,8192" > /sys/module/lowmemorykiller/parameters/minfree_screen_off;
			echo "64" > /sys/module/lowmemorykiller/parameters/cost;
			echo "4096" > /proc/sys/vm/mmap_min_addr;
		;;
		medium)
			echo "1024,2048,4096,8192,12288,16384" > /sys/module/lowmemorykiller/parameters/minfree_screen_off;
			echo "32" > /sys/module/lowmemorykiller/parameters/cost;
			echo "16384" > /proc/sys/vm/mmap_min_addr;
		;;
		aggressive)
			echo "2048,4096,8192,16384,24576,32768" > /sys/module/lowmemorykiller/parameters/minfree_screen_off;
			echo "16" > /sys/module/lowmemorykiller/parameters/cost;
			echo "16384" > /proc/sys/vm/mmap_min_addr;
		;;
		exterminate)
			echo "4096,8192,16384,32768,49152,65536" > /sys/module/lowmemorykiller/parameters/minfree_screen_off;
			echo "8" > /sys/module/lowmemorykiller/parameters/cost;
			echo "32768" > /proc/sys/vm/mmap_min_addr;
		;;
		*)
			oom_config_screen_off=medium;
		;;
	esac;
fi;

echo ${oom_config_screen_off};

