#!/sbin/busybox sh

# $1 - "oom_config_screen_off"
# $2 - value=

if [ "a$2" != "a" ]; then
	oom_config_screen_off=$2;

	case "${oom_config_screen_off}" in
	very_light)
		echo "512,1024,1280,2048,3072,4096" > /sys/module/lowmemorykiller/parameters/minfree_screen_off;
	;;
	light)
		echo "1024,2048,2560,4096,6144,8192" > /sys/module/lowmemorykiller/parameters/minfree_screen_off;
	;;
	medium)
		echo "1024,2048,4096,8192,12288,16384" > /sys/module/lowmemorykiller/parameters/minfree_screen_off;
	;;
	aggressive)
		echo "2048,4096,8192,16384,24576,32768" > /sys/module/lowmemorykiller/parameters/minfree_screen_off;
	;;
	exterminate)
		echo "4096,8192,16384,32768,49152,65536" > /sys/module/lowmemorykiller/parameters/minfree_screen_off;
	;;
	*)
		oom_config_screen_off=medium;
	;;
	esac;
fi;

echo ${oom_config_screen_off};

