#!/sbin/busybox sh

# $1 - "oom_config_screen_on"
# $2 - value=

PROFILE=$(cat /data/.siyah/.active.profile);
. /data/.siyah/${PROFILE}.profile;

if [ "$auto_oom" == 1 ]; then
	if [ "a$2" != "a" ]; then
		oom_config_screen_on=$2;

		case "${oom_config_screen_on}" in
			light)
				echo "1024,1024,1280,2048,16384,32768" > /sys/module/lowmemorykiller/parameters/minfree;
				echo "64" > /sys/module/lowmemorykiller/parameters/cost;
			;;
			low)
				echo "1024,2048,2560,4096,16384,32768" > /sys/module/lowmemorykiller/parameters/minfree;
				echo "32" > /sys/module/lowmemorykiller/parameters/cost;
			;;
			medium)
				echo "1024,2048,4096,8192,16384,32768" > /sys/module/lowmemorykiller/parameters/minfree;
				echo "32" > /sys/module/lowmemorykiller/parameters/cost;
			;;
			default)
				echo "1024,2048,4096,8192,16384,32768" > /sys/module/lowmemorykiller/parameters/minfree;
				echo "32" > /sys/module/lowmemorykiller/parameters/cost;
			;;
			aggressive)
				echo "2048,4096,8192,16384,24576,32768" > /sys/module/lowmemorykiller/parameters/minfree;
				echo "16" > /sys/module/lowmemorykiller/parameters/cost;
			;;
			exterminate)
				echo "4096,8192,16384,19200,21760,32768" > /sys/module/lowmemorykiller/parameters/minfree;
				echo "8" > /sys/module/lowmemorykiller/parameters/cost;
			;;
			*)
				oom_config_screen_on=medium;
			;;
		esac;
	fi;

	echo ${oom_config_screen_on};
fi;

