#!/sbin/busybox sh
(
SLEEPING=`cat /sys/power/wait_for_fb_sleep`
if [ "$SLEEPING" = "sleeping" ]; then
	sleep 1
	if [ -e /sys/class/misc/notification/led ]; then
		echo 1 > /sys/class/misc/notification/led
	fi
	if [ -e /sys/class/misc/backlightnotification/notification_led ]; then
		echo 1 > /sys/class/misc/backlightnotification/notification_led
	fi
fi
)&
echo Turn off the screen to test BLN.
