#!/sbin/busybox sh

# ZRAM
# Now we load the ZRAM as RAM SWAP and gain more compressed RAM.
# ZRAM compress ratio is 50% so if set 300MB, then it will give clean 150MB More RAM,
# This gives us 1GB RAM device or more.

# $1 - "zramtweaks"
# $2 - value=

if [ "a$2" == "a" ]; then
	echo "$zramtweaks";
else
	zramtweaks=$2;
	echo "$zramtweaks";
fi;

case "${zramtweaks}" in
	1)
		if [ `cat /proc/swaps | grep 150000 |  wc -l` != "1" ]; then
			if [ -e /dev/block/zram0 ]; then
				# for on the fly changes we need to shutdown ZRAM first
				swapoff /dev/block/zram0 >/dev/null 2>&1;
				echo "1" > /sys/block/zram0/reset;
				# setting size of ZRAM swap drive
				echo "153604000" > /sys/block/zram0/disksize;
				# creating SWAP from ZRAM drive
				mkswap /dev/block/zram0 >/dev/null;
				# activating ZRAM swap
				swapon /dev/block/zram0 >/dev/null 2>&1;
			fi;
		fi;
	;;
	2)
		if [ `cat /proc/swaps | grep 300000 |  wc -l` != "1" ]; then
			if [ -e /dev/block/zram0 ]; then
				# for on the fly changes we need to shutdown ZRAM first
				swapoff /dev/block/zram0 >/dev/null 2>&1;
				echo "1" > /sys/block/zram0/reset;
				# setting size of ZRAM swap drive
				echo "307202000" > /sys/block/zram0/disksize;
				# creating SWAP from ZRAM drive
				mkswap /dev/block/zram0 >/dev/null;
				# activating ZRAM swap
				swapon /dev/block/zram0 >/dev/null 2>&1;
			fi;
		fi;
	;;
	3)
		if [ `cat /proc/swaps | grep 600000 |  wc -l` != "1" ]; then
			if [ -e /dev/block/zram0 ]; then
				# for on the fly changes we need to shutdown ZRAM first
				swapoff /dev/block/zram0 >/dev/null 2>&1;
				echo "1" > /sys/block/zram0/reset;
				# setting size of RAM swap drive
				echo "614404000" > /sys/block/zram0/disksize;
				# creating SWAP from ZRAM drive
				mkswap /dev/block/zram0 >/dev/null;
				# activating ZRAM swap
				swapon /dev/block/zram0 >/dev/null 2>&1;
			fi;
		fi;
	;;
	4)
		if [ -e /dev/block/zram0 ]; then
			swapoff /dev/block/zram0 >/dev/null 2>&1;
			echo "1" > /sys/block/zram0/reset;
		fi;
	;;
	*)
		zramtweaks=4;
	;;
esac;

