#!/sbin/busybox sh
cd /;

BB=/sbin/busybox

$BB mount -t proc proc /proc;
$BB mount -t sysfs sysfs /sys;

# set "/" rw
$BB mount -t rootfs -o remount,rw rootfs;

if $BB grep -q bootmode=2 /proc/cmdline; then
	# recovery mode
	echo "0" > /proc/sys/kernel/rom_feature_set;
	$BB cp /res/images/recovery-icon.png /res/images/icon_clockwork.png;
	$BB cp -a /recovery.rc /init.rc;
	exec /sbin/init.recovery;
fi;

if $BB grep -q 1 /sys/class/power_supply/battery/batt_lp_charging; then
	# low power mode
	echo "0" > /proc/sys/kernel/rom_feature_set;
	$BB cp /res/images/recovery-icon.png /res/images/icon_clockwork.png;
	$BB cp -a lpm.rc init.rc;
	$BB rm init.smdk4210.rc;
	exec /sbin/init.recovery;
fi;

# unmount all sdcards before any folder cleaning
$BB umount -l /sdcard;
$BB umount -l /extSdCard;
$BB umount -l /mnt/sdcard;
$BB umount -l /storage/sdcard0;
$BB umount -l /storage/sdcard1;

# cleaning and rebuilding the /mnt and sdcards mounts folders
$BB rm -rf /sdcard;
$BB rm -rf /mnt;
$BB rm -rf /storage;
$BB rm -rf /vendor;
$BB rm -rf /tmp/*;
mkdir -p /dev/block;
mkdir /dev/input;
mkdir /dev/graphics;
mkdir -p /mnt/asec;
mkdir -p /mnt/.lfs;
mkdir -p /mnt/obb;
mkdir -p /mnt/secure;
mkdir -p /mnt/tmp;
mkdir -p /mnt/.secondrom;
$BB chmod -R 777 /mnt/;
mkdir /preload;
chmod 0771 /preload;
chown system:system /preload;
mkdir /storage;
$BB chmod -R 777 /storage;
mknod /dev/graphics/fb0 c 29 0
mknod /dev/input/event1 c 13 65
mknod /dev/input/event2 c 13 66
mknod /dev/input/event8 c 13 72
mknod /dev/input/event9 c 13 73
mknod /dev/ashmem c 10 61
mknod /dev/block/mmcblk0p7 b 179 7
mknod /dev/block/mmcblk0p9 b 259 1
mknod /dev/block/mmcblk0p10 b 259 2
mknod /dev/block/mmcblk0p11 b 259 3
mknod /dev/block/mmcblk0p12 b 259 4
mknod /dev/block/loop0 b 7 0

# dual boot check and run
$BB mount -t ext4 -o rw /dev/block/mmcblk0p12 /preload;
$BB mount -t vfat /dev/block/mmcblk0p11 /mnt/tmp && ( mkdir -p /mnt/tmp/clockworkmod/blobs/ ) && ( touch /mnt/tmp/clockworkmod/.nomedia ) && ( touch /mnt/tmp/clockworkmod/blobs/.nomedia );

if [ -e /mnt/tmp/.nextboot ]; then
	NEXTBOOT=`cat /mnt/tmp/.nextboot`;
	$BB rm /mnt/tmp/.nextboot;
fi;
if [ -e /mnt/tmp/.defaultrom ]; then
	DEFAULTROM=`cat /mnt/tmp/.defaultrom`;
fi;
SECONDROM=1;
NOBOOTLOGO=0;
[ -f /preload/build.prop ] || SECONDROM=0;
[ -f /mnt/tmp/.secondrom/data.img ] || SECONDROM=0;
[ -f /mnt/tmp/.secondrom/cache.img ] || SECONDROM=0;
[ -f /mnt/tmp/.nobootlogo ] && NOBOOTLOGO=1;
sync;
$BB umount -l /mnt/tmp;

if [ "$SECONDROM" == "0" ]; then
	if [ "$NOBOOTLOGO" == "0" ]; then
		/sbin/choose_rom 0;
	fi;
else
	if [ "$NEXTBOOT" == "1" ]; then
		SECONDROM=0;
	elif [ "$NEXTBOOT" == "2" ]; then
		SECONDROM=1;
	else
		if [ "$NOBOOTLOGO" == "1" ]; then
			SECONDROM=$DEFAULTROM;

		elif [ "$DEFAULTROM" == "1" ]; then
			/sbin/choose_rom $SECONDROM;

			if [ "$?" == "1" ]; then
				SECONDROM=0;
			else
				SECONDROM=1;
			fi;
		else
			/sbin/choose_rom $SECONDROM;

			if [ "$?" == "1" ]; then
				SECONDROM=1;
			else
				SECONDROM=0;
			fi;
		fi;
	fi;
fi;

if [ "$SECONDROM" == "1" ]; then
	$BB rm -rf /res/dev;
	mkdir -p /res/dev;
	ln -s /mnt/.secondrom/.secondrom/data.img /res/dev/data;
	ln -s /dev/block/mmcblk0p12 /res/dev/system;
	ln -s /mnt/.secondrom/.secondrom/cache.img /res/dev/cache;
else
	$BB rm -rf /res/dev;
	mkdir -p /res/dev;
	ln -s /dev/block/mmcblk0p10 /res/dev/data;
	ln -s /dev/block/mmcblk0p9 /res/dev/system;
	ln -s /dev/block/mmcblk0p7 /res/dev/cache;
fi;

SECROM_FUNCTION_AOSP()
{
	# init.rc style JB/CM/AOKP
	if [ "$SECONDROM" == "1" ]; then
		$BB mv /init.smdk4210.rc.2 /init.smdk4210.rc;
		$BB rm /init.rc.2;
	else
		$BB rm /init.smdk4210.rc.2;
		$BB rm /init.rc.2;
	fi;
}

SECROM_FUNCTION_SAMMY()
{
	# init.rc style SAMMY ICS
	if [ "$SECONDROM" == "1" ]; then
		$BB mv /init.smdk4210.rc.2 /init.smdk4210.rc;
		$BB mv /init.rc.2 /init.rc
	else
		$BB rm /init.smdk4210.rc.2;
		$BB rm /init.rc.2;
	fi;
}

# mounting system!
$BB mount -t ext4 /res/dev/system /system;

# linking /system/bin to /bin for crond
ln -s /system/bin/ /bin

# adding latest vendor binary from 3.6.RC6 kernel for all! tested working great
mkdir -p /system/vendor/firmware;
$BB cp -a /res/misc/vendor/firmware/mfc_fw.bin /system/vendor/firmware/mfc_fw.bin;
$BB chmod 755 /system/vendor/firmware/mfc_fw.bin;

# fix permission to services.jar in case user did a mess, after using my MOD!
$BB chmod 644 /system/framework/services.jar;

# copy new Kernel modules to /system/lib/modules and to second rom system if exist
if [ ! -d /system/lib/modules ]; then
	mkdir /system/lib/modules;
	$BB cp /lib/modules/*.ko /system/lib/modules/;
	$BB chmod 755 /system/lib/modules/*.ko;
else
	$BB rm -f /system/lib/modules/*.ko;
	$BB cp /lib/modules/*.ko /system/lib/modules/;
	$BB chmod 755 /system/lib/modules/*.ko;
fi;

if [ -f /system/recovery.cpio.gz ]; then
	$BB mount -o remount,rw /;
	$BB zcat /system/recovery.cpio.gz | cpio -idmu;
fi;

B2G=0;
MIUI_JB=0;
JELLY=0;
AOSP=1;
S4A=0;
JBSAMMY=0;
CM_AOKP_10_JB=0;
$BB echo "0" > /tmp/jbsammy_installed;
$BB chmod 666 /tmp/jbsammy_installed;

[ "`$BB grep -i cMIUI /system/build.prop`" ] && MIUI_JB=1;
[ "`$BB grep -i android-htc-rev /system/build.prop`" ] && S4A=1;
[ "`$BB grep -i ro.build.PDA=I9100XXLSJ /system/build.prop`" ] && JBSAMMY=1;
[ "`$BB grep -i ro.build.PDA=I9100XWLS8 /system/build.prop`" ] && JBSAMMY=1;
B2G=`$BB ls /system/b2g | wc -l`;
JELLY=`$BB ls /system/lib/ssl/engines/libkeystore.so | wc -l`;
# has to be negative! for SAMMY ICS ROM to get his init files.
AOSP=`$BB ls /system/framework/framework2.jar | wc -l`;
CM_AOKP_10_JB=`$BB ls /system/bin/wfd | wc -l`;

# one more time set "/" rw just for good sleep
$BB mount -t rootfs -o remount,rw rootfs;

#############################
# Partition global tuning!
#############################

PARTITION_TUNING()
{
	DEVICE_DATA="/res/dev/data";
	DIR_DATA="/data";
	LOG_DATA="/log-data";
	LOG_DATA_TMP="/log-data-tmp";

	DEVICE_CACHE="/res/dev/cache";
	DIR_CACHE="/cache";
	LOG_CACHE="/log-cache";
	LOG_CACHE_TMP="/log-cache-tmp";

	# new empty log
	$BB sh -c "/sbin/date" > $LOG_DATA;
	$BB sh -c "/sbin/date" > $LOG_CACHE;

	# umount 
	$BB umount -l $DIR_DATA >> $LOG_DATA 2>&1;
	$BB umount -l $DIR_CACHE >> $LOG_CACHE 2>&1;

	# set fs-feature -> [^]has_journal
	$BB sh -c "/sbin/tune2fs -l $DEVICE_CACHE | grep 'features' | grep 'has_journal'" > $LOG_CACHE_TMP;
	if [ "a`cat $LOG_CACHE_TMP`" == "a" ]; then
		$BB sh -c "/sbin/tune2fs -O has_journal $DEVICE_CACHE" >> $LOG_CACHE 2>&1;
		$BB sh -c "/sbin/e2fsck -p $DEVICE_CACHE" >> $LOG_CACHE 2>&1;
	fi;
	$BB sh -c "/sbin/tune2fs -l $DEVICE_DATA | grep 'features' | grep 'has_journal'" > $LOG_DATA_TMP;
	if [ "a`cat $LOG_DATA_TMP`" == "a" ]; then
		$BB sh -c "/sbin/tune2fs -O has_journal $DEVICE_DATA" >> $LOG_DATA 2>&1;
		$BB sh -c "/sbin/e2fsck -p $DEVICE_DATA" >> $LOG_DATA 2>&1;
	fi;

	# set fs-feature -> [^]dir_index
	$BB sh -c "/sbin/tune2fs -l $DEVICE_CACHE | grep 'features' | grep 'dir_index'" > $LOG_CACHE_TMP;
	if [ "a`cat $LOG_CACHE_TMP`" == "a" ]; then	
		$BB sh -c "/sbin/tune2fs -O dir_index $DEVICE_CACHE" >> $LOG_CACHE 2>&1;
	fi;
	$BB sh -c "/sbin/tune2fs -l $DEVICE_DATA | grep 'features' | grep 'dir_index'" > $LOG_DATA_TMP;
	if [ "a`cat $LOG_DATA_TMP`" == "a" ]; then
		$BB sh -c "/sbin/tune2fs -O dir_index $DEVICE_DATA" >> $LOG_DATA 2>&1;
	fi;

	# set mount option -> [^]journal_data_ordered
	$BB sh -c "/sbin/tune2fs -l $DEVICE_CACHE | grep 'Default mount options' | grep 'journal_data_ordered'" > $LOG_CACHE_TMP;
	if [ "a`cat $LOG_CACHE_TMP`" == "a" ]; then
		$BB sh -c "/sbin/tune2fs -o journal_data_ordered $DEVICE_CACHE" >> $LOG_CACHE 2>&1;
		$BB sh -c "/sbin/e2fsck -p $DEVICE_CACHE" >> $LOG_CACHE 2>&1;
	fi;
	$BB sh -c "/sbin/tune2fs -l $DEVICE_DATA | grep 'Default mount options' | grep 'journal_data_ordered'" > $LOG_DATA_TMP;
	if [ "a`cat $LOG_DATA_TMP`" == "a" ]; then
		$BB sh -c "/sbin/tune2fs -o journal_data_ordered $DEVICE_DATA" >> $LOG_DATA 2>&1;
		$BB sh -c "/sbin/e2fsck -p $DEVICE_DATA" >> $LOG_DATA 2>&1;
	fi;

	# set inode to 256
	$BB sh -c "/sbin/tune2fs -l $DEVICE_CACHE | grep 'Inode size' | grep '256'" > $LOG_CACHE_TMP;
	if [ "a`cat $LOG_CACHE_TMP`" == "a" ]; then
		$BB sh -c "/sbin/tune2fs -I 256 $DEVICE_CACHE" >> $LOG_CACHE 2>&1;
		$BB sh -c "/sbin/e2fsck -p $DEVICE_CACHE" >> $LOG_CACHE 2>&1;
	fi;
	$BB sh -c "/sbin/tune2fs -l $DEVICE_DATA | grep 'Inode size' | grep '256'" > $LOG_DATA_TMP;
	if [ "a`cat $LOG_DATA_TMP`" == "a" ]; then
		$BB sh -c "/sbin/tune2fs -I 256 $DEVICE_DATA" >> $LOG_DATA 2>&1;
		$BB sh -c "/sbin/e2fsck -p $DEVICE_DATA" >> $LOG_DATA 2>&1;
	fi;

	# only if asked by user via stweaks
	if [ -e /system/run_fs_check ]; then
		# reset the lock-file
		$BB rm -f /system/run_fs_check

		# check cache
		$BB sh -c "/sbin/e2fsck -p $DEVICE_CACHE" >> $LOG_CACHE 2>&1;
		$BB sh -c "/sbin/tune2fs -l $DEVICE_CACHE | grep 'Filesystem state' | grep 'clean'" > $LOG_CACHE_TMP;
		if [ "a`cat $LOG_CACHE_TMP`" == "a" ] || [ "`cat $LOG_CACHE_TMP`" == "Filesystem state:         clean with errors" ]; then
			$BB sh -c "/sbin/e2fsck -fyc $DEVICE_CACHE" >> $LOG_CACHE 2>&1;
			$BB sh -c "/sbin/e2fsck -p $DEVICE_CACHE" >> $LOG_CACHE 2>&1;
		else
			echo "CACHE: $LOG_CACHE_TMP" >> $LOG_CACHE 2>&1;
		fi;

		# check data
		$BB sh -c "/sbin/e2fsck -p $DEVICE_DATA >> $LOG_DATA 2>&1";
		$BB sh -c "/sbin/tune2fs -l $DEVICE_DATA | grep 'Filesystem state' | grep 'clean'" > $LOG_DATA_TMP;
		if [ "a`cat $LOG_DATA_TMP`" == "a" ] || [ "`cat $LOG_DATA_TMP`" == "Filesystem state:         clean with errors" ]; then
			$BB sh -c "/sbin/e2fsck -fyc $DEVICE_DATA" >> $LOG_DATA 2>&1;
			$BB sh -c "/sbin/e2fsck -p $DEVICE_DATA" >> $LOG_DATA 2>&1;
		else
			echo "DATA: $LOG_DATA_TMP" >> $LOG_DATA 2>&1;
		fi;
	fi;
}

USER_ACTIONS()
{
	if [ "$JELLY" == "1" ] || [ "$MIUI_JB" == "1" ] || [ "$CM_AOKP_10_JB" == "1" ] || [ "$JBSAMMY" == "1" ]; then
		echo "JB-INSTALLED" > /sbin/ext/jb-installed; # used and terminated at /sbin/ext/partition_tune.sh
		stop adbd;

		if [ "$JBSAMMY" == "0" ]; then
			if [ "$CM_AOKP_10_JB" == "1" ] || [ "$JELLY" == "1" ]; then
				$BB cp -a /sbin/adbd.cm10-1 /sbin/adbd;
				$BB chmod 755 /sbin/adbd;
				start adbd;
			else
				start adbd;
			fi;
		else
			$BB cp -a /sbin/adbd.jb /sbin/adbd;
			$BB chmod 755 /sbin/adbd;
			start adbd;
		fi;
	fi;

	# only if asked by user via stweaks
	if [ -e /system/run_fix_media ]; then
		# data mount
		$BB mount -t ext4 /res/dev/data /data;

		mkdir /sdcardtmp;
		$BB chmod 777 /sdcardtmp;
		$BB mount -t vfat /dev/block/mmcblk0p11 /sdcardtmp;
		$BB rm /system/run_fix_media;

		if [ -e /sdcard/Android/data/ ]; then
			$BB rm -rf /sdcardtmp/Android/data/com.cooliris.media;
			$BB rm -rf /sdcardtmp/Android/data/com.android.gallery3d;
			$BB rm -rf /sdcardtmp/Android/data/com.google.android.gallery3d;
			$BB rm -rf /sdcardtmp/Android/data/com.android.providers.media;
			$BB rm -rf /sdcardtmp/Android/data/com.google.android.music;
			$BB rm -rf /data/data/com.android.providers.media/databases/*;
		fi;
		# sdcard unmount
		sync;
		$BB umount -l /sdcardtmp;
		if [ `du -h /sdcardtmp | grep 4 | cut -c1-4` == "4.0K" ]; then
			$BB rm -rf /sdcardtmp;
		fi;

		# data unmount
		sync;
		$BB umount -l /data;
	fi;
}

BOOTROM()
{
	PARTITION_TUNING;
	USER_ACTIONS;
	$BB rm -f /sbin/mount;
	exec /sbin/init.samsung;
}

# network tuning reset to allow real ROM control over H/H+/3G/G signal.
$BB sed -i "s/ro.ril.hsxpa=[0-9]*//g" /system/build.prop;
$BB sed -i "s/ro.ril.gprsclass=[0-9]*//g" /system/build.prop;

# system dalvik.vm tuning.
$BB sed -i "s/dalvik.vm.heapsize=[0-9a-zA-Z]*/dalvik.vm.heapsize=128m/g" /system/build.prop;
$BB sed -i "s/dalvik.vm.heapstartsize=[0-9a-zA-Z]*/dalvik.vm.heapstartsize=24m/g" /system/build.prop;
$BB sed -i "s/dalvik.vm.heapgrowthlimit=[0-9a-zA-Z]*/dalvik.vm.heapgrowthlimit=128m/g" /system/build.prop;

# we can OC to 1.5Ghz.
$BB sed -i "s/ro.device.cpu=Dual-core 1.2GHz ARM Cortex-A9/ro.device.cpu=Dual-core 1.5GHz ARM Cortex-A9/g" /system/build.prop;

######################################
# Starting ROM choose and INIT config.
######################################

if [ "$S4A" == "1" ]; then
	echo "0" > /proc/sys/kernel/rom_feature_set;
	$BB cp -a /res/misc/Sense4All-ROM/init.s4a /init.rc;
	$BB cp -a /res/misc/Sense4All-ROM/init.s4a.2 /init.rc.2;

	SECROM_FUNCTION_SAMMY;

elif [ "$B2G" == "1" ]; then
	echo "0" > /proc/sys/kernel/rom_feature_set;
	$BB cp -a /res/misc/B2G-ROM/* /;

	SECROM_FUNCTION_SAMMY;

elif [ "$JBSAMMY" == "1" ]; then
	echo "2" > /proc/sys/kernel/rom_feature_set;
	$BB cp -a /res/misc/JellyB-Sammy/* /;
	echo "1" > /tmp/jbsammy_installed;

	# FIX HOME BUTTON JBSAMMY 
	GPIOKEYS="/system/usr/keylayout/gpio-keys.kl";
	if [ -e $GPIOKEYS ]; then
		KHCOUNT=`cat $GPIOKEYS | grep "172" -c`;
		if [ $KHCOUNT == 1 ]; then
			sed -i 's/172/102/g' $GPIOKEYS;
		fi;
	fi;

	SECROM_FUNCTION_AOSP;

elif [ "$CM_AOKP_10_JB" == "1" ]; then
	# Injecting JB Modded by Dorimanx, SUPER libsqlite!
	$BB cp -a /res/misc/sql/jb/libsqlite.so /system/lib/libsqlite.so;
	$BB cp -a /res/misc/sql/jb/sqlite3 /system/xbin/sqlite3;
	$BB chmod 755 /system/lib/libsqlite.so;
	$BB chmod 755 /system/xbin/sqlite3;
	echo "3" > /proc/sys/kernel/rom_feature_set;
	$BB cp -a /res/misc/JellyB-CM-AOKP-10.1/* /;

	SECROM_FUNCTION_AOSP;

elif [ "$JELLY" == "1" ] || [ "$MIUI_JB" == "1" ]; then
	# Injecting JB Modded by Dorimanx, SUPER libsqlite!
	$BB cp -a /res/misc/sql/jb/libsqlite.so /system/lib/libsqlite.so;
	$BB cp -a /res/misc/sql/jb/sqlite3 /system/xbin/sqlite3;
	$BB chmod 755 /system/lib/libsqlite.so;
	$BB chmod 755 /system/xbin/sqlite3;

	echo "3" > /proc/sys/kernel/rom_feature_set;
	$BB cp -a /res/misc/JellyB-CM-AOKP/* /;

	SECROM_FUNCTION_AOSP;

elif [ "$AOSP" == "0" ]; then
	# Injecting ICS Modded by Dorimanx, SUPER libsqlite!
	$BB cp -a /res/misc/sql/ics/libsqlite.so /system/lib/libsqlite.so;
	$BB chmod 755 /system/lib/libsqlite.so;
	echo "1" > /proc/sys/kernel/rom_feature_set;
	$BB cp -a /res/misc/CM-ROM/* /;

	SECROM_FUNCTION_AOSP;
else
	# If not detected Known ROM, then SAMMY ICS ROM installed.
	echo "0" > /proc/sys/kernel/rom_feature_set;

	SECROM_FUNCTION_SAMMY;
fi;

# if found by ROM detector and function finished, boot the detected ROM.
BOOTROM;

