#!/sbin/busybox sh

mount -t rootfs -o remount,rw rootfs

ln -s /sbin/busybox /sbin/sh

BB=/sbin/busybox

# protecting fuelgauge reset trigger.
chmod 000 /sys/devices/platform/i2c-gpio.9/i2c-9/9-0036/power_supply/fuelgauge/fg_reset_soc

rm -rf /emmc
mkdir /emmc
chmod 777 /emmc

rm -rf /sdcard
mkdir /sdcard
chmod 777 /sdcard

rm -rf /etc
mkdir /etc
cat /res/etc/recovery.fstab > /etc/recovery.fstab

#start adbd
stop tvout

rm -rf /cache
mkdir /cache
chmod 777 /cache
mount -t ext4 /dev/block/mmcblk0p7 /cache
mkdir /cache/recovery
chmod 770 /cache/recovery
chown system.cache /cache/recovery

cd /
mkdir -p /mnt/.secondrom
mount -t vfat /dev/block/mmcblk0p11 /mnt/.secondrom
mkdir /mnt/.secondrom/.secondrom
rm -rf /secondrom_cache
mkdir /secondrom_cache
mount -t ext4 /mnt/.secondrom/.secondrom/cache.img /secondrom_cache
mkdir /secondrom_data
mkdir /secondrom_system

echo "75" > /sys/vibrator/pwm_val
echo 102 > /sys/devices/virtual/sec/sec_key/set_homekey

if [ -f /cache/recovery/command ]; then
	$BB cp /res/keys-samsung /res/keys
	recovery-samsung
else
	echo 1 > /sbin/recovery-is-running
	recovery
fi;

