#!/sbin/busybox sh

TMPFILE=$(mktemp -t)

(
	TESTCONNECTION=`wget http://www.google.com -O $TMPFILE &>/dev/null 2>&1`
	if [ $? != 0 ]; then
		echo "Problem: no internet connection";
		xzcat /res/misc/hosts.xz > $TMPFILE;
		mv -f $TMPFILE /system/etc/hosts;
	else
		wget http://winhelp2002.mvps.org/hosts.zip -O $TMPFILE &>/dev/null 2>&1;
		unzip $TMPFILE HOSTS &>/dev/null 2>&1;
		mv -f /tmp/HOSTS /system/etc/hosts;
	fi;
	chmod 622 /system/etc/hosts;
)&
echo "New AD Blocker Installed to /system/etc/hosts"

