#!/sbin/busybox sh

case "$2" in
	0)
		echo "nothnig to do";
	;;
	1)
		PROFILE=`cat /data/.siyah/.active.profile`;
		echo "1" > /sys/devices/platform/samsung-pd.2/mdnie/mdnie/mdnie/user_mode;
		echo "127" > /sys/devices/platform/samsung-pd.2/mdnie/mdnie/mdnie/user_cb;
		echo "127" > /sys/devices/platform/samsung-pd.2/mdnie/mdnie/mdnie/user_cr;
		sed -i "s/user_cb=[0-9]*/user_cb=127/g" /data/.siyah/$PROFILE.profile;
		sed -i "s/user_cr=[0-9]*/user_cr=127/g" /data/.siyah/$PROFILE.profile;
		echo "Color was set to default, reloading";
		sleep 2
		pkill -f "com.gokhanmoral.stweaks.app";
		am start -a android.intent.action.MAIN -n com.gokhanmoral.stweaks.app/.MainActivity;		
	;;
	*)
		echo "need input, 0=nothing, 1=reset color";
	;;
esac;

