#!/sbin/busybox sh
export PATH="/res/customconfig/actions/push-actions:${PATH}";

if [ "a$1" == "a" ]; then
	echo $config_backup_restore;
else
	config_backup_restore=$1;
	echo $config_backup_restore;
fi;

case "${config_backup_restore}" in
	1)
		echo "Backup config file ...";
		PROFILE=$(cat /data/.siyah/.active.profile);

		cp /data/.siyah/$PROFILE.profile /data/.siyah/$PROFILE.profile_backup;
		;;
	2)
		echo "Restoring config file ...";
		PROFILE=$(cat /data/.siyah/.active.profile);

		file1=/data/.siyah/$PROFILE.profile;
		file2=/data/.siyah/$PROFILE.profile_backup;

		i=1;
		while read line1; do
			line2=$(sed -n "$i p" $file2);
			line2_1=$(echo $line2 | cut -f 1 -d '=');
			line2_2=$(echo $line2 | cut -f 2 -d '=');
			line1_1=$(echo $line1 | cut -f 1 -d '=');
			line1_2=$(echo $line1 | cut -f 2 -d '=');
			if [ "a${line1_2}" != "a${line2_2}" ]; then
				if [ "${line2_2}" != "" ]; then
					sed -i "s/$line1_1\=$line1_2/$line2_1\=$line2_2/g" $file1;
				fi;
			fi;
			i=$(($i+1));
		done<$file1
		;;
	*)
		echo "need input, 1=backup; 2=restore";
		;;
esac;
