#!/sbin/busybox sh
export PATH="/res/customconfig/actions/push-actions:${PATH}";

if [ "a$2" == "a" ]; then
	echo $config_backup_restore;
else
	config_backup_restore=$2;
	echo $config_backup_restore;
fi;

case "${config_backup_restore}" in
	3)
		file2=/res/customconfig/battery.profile;
		echo "battery" > /data/.siyah/.active.profile;
		config_backup_restore=2;
	;;
	4)
		file2=/res/customconfig/default.profile;
		echo "default" > /data/.siyah/.active.profile;
		config_backup_restore=2;
	;;
	5)
		file2=/res/customconfig/performance.profile;
		echo "performance" > /data/.siyah/.active.profile;
		config_backup_restore=2;
	;;
	6)
		file2=/res/customconfig/extreme_battery.profile;
		echo "battery" > /data/.siyah/.active.profile;
		config_backup_restore=2;
	;;
	7)
		file2=/res/customconfig/extreme_performance.profile;
		echo "performance" > /data/.siyah/.active.profile;
		config_backup_restore=2;
	;;
	*)
		file2=/data/.siyah/$PROFILE.profile_backup;
	;;
esac;

LOCK_FILE="/data/.siyah/restore_running";
PROFILE=`cat /data/.siyah/.active.profile`;

case "${config_backup_restore}" in
	1)
		echo "Backup config file ...";
		cp /data/.siyah/$PROFILE.profile /data/.siyah/$PROFILE.profile_backup;
		cp /data/.siyah/$PROFILE.profile /sdcard/$PROFILE.profile_backup;
		echo "Backup Done!";
	;;
	2)
		file1="/data/.siyah/${PROFILE}.profile";

		if [ ! -f $file1 ] || [ ! -f $file2 ]; then
			echo "File not found!";
			exit;
		fi;

		if [ ! -e $LOCK_FILE ]; then
			echo "restoring" > $LOCK_FILE;
			echo "Restoring config file ...";
			echo "Wait 90Sec till full restore, app will restart with new settings.";
			(
				# read in file1->line1
				while read line1; do
					# split the config into variables where we find "="
					line1_1=$(echo $line1 | cut -f 1 -d '=');
					line1_2=$(echo $line1 | cut -f 2 -d '=');

					# grep the content from backup-file ...
					line2=$(grep "^${line1_1}\=" $file2)
					# ... and also split into variables
					line2_1=$(echo $line2 | cut -f 1 -d '=');
					line2_2=$(echo $line2 | cut -f 2 -d '=');

					# compare config- and backup-file
					if [ "a${line1_1}" != "a${line2_1}" ]; then
						# nothing to do -> continue the loop
						continue;
					else
						# if backup-file has different values, then restore it
						if [ "a${line1_2}" != "a${line2_2}" ]; then
							if [ "${line2_2}" != "" ]; then
								sed -i "s/${line1_1}\=${line1_2}/${line2_1}\=${line2_2}/g" $file1;
							fi;
						else
							# nothing to do -> continue the loop
							continue;
						fi;
					fi;
				done<$file1

				# hiding all push action scripts from uci.sh
				/sbin/busybox mount -o remount,rw rootfs;
				/sbin/busybox mv /res/customconfig/actions/push-actions/* /res/no-push-on-boot/;

				# apply New ExTweaks settings
				/res/uci.sh apply;

				# restore all the PUSH Button Actions back to there location
				/sbin/busybox mount -o remount,rw rootfs;
				/sbin/busybox mv /res/no-push-on-boot/* /res/customconfig/actions/push-actions/;

				# wait for full sync ...
				sync;

				# Killing extweaks, if was open it's will restart!
				EXTWEAKSAPP=`pgrep -f "com.darekxan.extweaks.app"`;
				kill $EXTWEAKSAPP;

				rm -f $LOCK_FILE;
			)&
		else
			# Anti smart user protection! multi run of this script will bring HELL!
			echo "you are running RESTORE already! please wait!";
		fi;
	;;
	*)
		echo "need input, 1=backup; 2=restore";
	;;
esac;

