#!/sbin/busybox sh
export PATH="/res/customconfig/actions/push-actions:${PATH}";

if [ "a$2" == "a" ]; then
	echo $config_backup_restore;
else
	config_backup_restore=$2;
	echo $config_backup_restore;
fi;

PROFILE=`cat /data/.siyah/.active.profile`;

case "${config_backup_restore}" in
	3)
		file2=/res/customconfig/battery.profile;
		config_backup_restore=2;
	;;
	4)
		file2=/res/customconfig/default.profile;
		config_backup_restore=2;
	;;
	5)
		file2=/res/customconfig/performance.profile;
		config_backup_restore=2;
	;;
	6)
		file2=/res/customconfig/extra_battery.profile;
		config_backup_restore=2;
	;;
	7)
		file2=/res/customconfig/extra_performance.profile;
		config_backup_restore=2;
	;;
	*)
		file2=/data/.siyah/$PROFILE.profile_backup;
	;;
esac;

case "${config_backup_restore}" in
	1)
		echo "Backup config file ...";
		cp /data/.siyah/$PROFILE.profile /data/.siyah/$PROFILE.profile_backup;
		cp /data/.siyah/$PROFILE.profile /sdcard/$PROFILE.profile_backup;
		echo "Backup Done!";
	;;
	2)
		file1=/data/.siyah/$PROFILE.profile;

		if [ ! -f $file1 ] || [ ! -f $file2 ]; then
			echo "File not found!";
			exit;
		fi;

		if [ `pgrep -f push-actions/config_backup_restore |  wc -l` \< 3 ]; then
			echo "Restoring config file ...";
			echo "Wait 90Sec till full restore, app will restart with new settings.";
			(
				# read in file1->line1
				while read line1; do
					# split the config into variables where we find "="
					line1_1=$(echo $line1 | cut -f 1 -d '=');
					line1_2=$(echo $line1 | cut -f 2 -d '=');

					# grep the content from backup-file ...
					line2=$(grep "^$line1_1\=" $file2)
					# ... and also split into variables
					line2_1=$(echo $line2 | cut -f 1 -d '=');
					line2_2=$(echo $line2 | cut -f 2 -d '=');

					# compare config- and backup-file
					if [ "a${line1_1}" != "a${line2_1}" ]; then
						# nothing to do -> continue the loop
						continue;
					else
						# if backup-file has different values, then restore it
						if [ "a${line1_2}" != "a${line2_2}" ]; then
							echo $line1_2 " -> " $line2_2;

							if [ "${line2_2}" != "" ]; then
								sed -i "s/$line1_1\=$line1_2/$line2_1\=$line2_2/g" $file1;
							fi;
						else
							# nothing to do -> continue the loop
							continue;
						fi;
					fi;
				done<$file1

				# hiding all push action scripts from uci.sh
				/sbin/busybox mount -o remount,rw rootfs
				/sbin/busybox mv /res/customconfig/actions/push-actions/* /res/no-push-on-boot/

				# apply New ExTweaks settings
				/res/uci.sh apply
				# add trigger for push actions restore function
				echo "uci done" > /data/.siyah/uci_loaded
			)&

			# starting loop to wait till uci.sh apply finish working
			(
				while [ ! -e /data/.siyah/uci_loaded ]; do
					sleep 5;
					echo "Still waiting till all DONE!";
				done;

				# restore all the PUSH Button Actions back to there location
				/sbin/busybox mount -o remount,rw rootfs;
				/sbin/busybox mv /res/no-push-on-boot/* /res/customconfig/actions/push-actions/;
				/sbin/busybox rm -f /data/.siyah/uci_loaded;

				# wait for full sync
				sync;
				sleep 20;

				# Killing extweaks, if was open it's will restart!
				EXTWEAKSAPP=`pgrep -f "com.darekxan.extweaks.app"`;
				kill $EXTWEAKSAPP;
			)&
		else
			# Anti smart user protection! multi run of this script will bring HELL!
			echo "you are running RESTORE already! please wait!";
		fi;
	;;
	*)
		echo "need input, 1=backup; 2=restore";
	;;
esac;

