#!/sbin/busybox sh

(
CORTEX_CHECK=-1
CORTEX_CHECK=`pgrep -f "/sbin/busybox sh /sbin/ext/cortexbrain-tune.sh"`
if [ "1$CORTEX_CHECK" \> 10 ]; then
	echo "SERVICE ONLINE"
else
	echo "SERVICE OFFLINE"
fi;
)&

