#!/sbin/busybox sh

if [ ! -e /data/crontab/cron-clear-file-cache ]; then
	echo "no data" > /data/crontab/cron-clear-file-cache;
fi;
cat /data/crontab/cron-clear-file-cache > /data/crontab/cron_log;
echo "----------------------------" >> /data/crontab/cron_log;
if [ ! -e /data/crontab/cron-clear-ram-cache ]; then
	echo "no data" > /data/crontab/cron-clear-ram-cache;
fi;
cat /data/crontab/cron-clear-ram-cache >> /data/crontab/cron_log;
echo "----------------------------" >> /data/crontab/cron_log;
if [ ! -e /data/crontab/cron-fix_permissions ]; then
	echo "no data" > /data/crontab/cron-fix_permissions;
fi;
cat /data/crontab/cron-fix_permissions >> /data/crontab/cron_log;
echo "----------------------------" >> /data/crontab/cron_log;
if [ ! -e /data/crontab/cron-zipaling ]; then
	echo "no data" > /data/crontab/cron-zipaling;
fi;
cat /data/crontab/cron-zipaling >> /data/crontab/cron_log;

# push all to one log.
CRON_LOG=`cat /data/crontab/cron_log`;
echo $CRON_LOG;

