#!/sbin/busybox sh
export PATH="/res/customconfig/actions/push-actions:${PATH}";

if [ "a$2" == "a" ]; then
	echo $debug_to_sd;
else
	debug_to_sd=$2;
	echo $debug_to_sd;
fi;

case "${debug_to_sd}" in
	1)

	# Kernel-Info
	echo "Kernel-Version:" > /sdcard/dorimanx_debug;
	cat /proc/version >> /sdcard/dorimanx_debug;
	date +"Last Reboot: %d.%m.%y / %H:%m" -d @$(( $(date +%s) - $(cut -f1 -d. /proc/uptime) )) >> /sdcard/dorimanx_debug;
	lsmod >> /sdcard/dorimanx_debug;
	echo "" >> /sdcard/dorimanx_debug;

	# Memory
	echo "Memory-Info:" >> /sdcard/dorimanx_debug;
	free >> /sdcard/dorimanx_debug;
	cat /proc/meminfo >> /sdcard/dorimanx_debug;
	echo "" >> /sdcard/dorimanx_debug;

	# CPU
	echo "CPU-Info:" >> /sdcard/dorimanx_debug;
	scaling_governor=$(cat /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor)
	echo "CPU-Governor: $scaling_governor";
        cpuinfo_cur_freq=$(cat /sys/devices/system/cpu/cpu0/cpufreq/cpuinfo_cur_freq);
        echo "Cur.-Freq: $cpuinfo_cur_freq" >> /sdcard/dorimanx_debug;
        scaling_max_freq=$(cat /sys/devices/system/cpu/cpu0/cpufreq/scaling_max_freq);
        echo "Max.-Freq: $scaling_max_freq" >> /sdcard/dorimanx_debug;
        scaling_min_freq=$(cat /sys/devices/system/cpu/cpu0/cpufreq/scaling_min_freq);
        echo "Min.-Freq: $scaling_min_freq" >> /sdcard/dorimanx_debug;
	total_trans=$(cat /sys/devices/system/cpu/cpu0/cpufreq/stats/total_trans);
	echo "Total freq-switch: $total_trans" >> /sdcard/dorimanx_debug; 
	echo "Time-In-State:" >> /sdcard/dorimanx_debug;
	cat /sys/devices/system/cpu/cpu0/cpufreq/stats/time_in_state >> /sdcard/dorimanx_debug;
	for i in `cat /sys/devices/system/cpu/cpu0/cpufreq/stats/time_in_state | cut -f 2 -d ' '`; do 
		summe=$(($summe+$i)); 
	done; 
	summe=$(($summe/60)); 
	summe=$(($summe/60)); 
	summe=$(($summe/100)); 
	echo "uptime with CPU on: $summe h" >> /sdcard/dorimanx_debug;
	uptime >> /sdcard/dorimanx_debug;
	#cat /proc/loadavg >> /sdcard/dorimanx_debug;
	cpuinfo_cur_freq=$(cat /sys/devices/system/cpu/cpu0/cpufreq/cpuinfo_cur_freq);
	for i in `ls /sys/devices/system/cpu/cpu0/cpufreq/`; do
		echo $i >> /sdcard/dorimanx_debug;
		cat  /sys/devices/system/cpu/cpu0/cpufreq/$i >> /sdcard/dorimanx_debug;
	done;
	echo "" >> /sdcard/dorimanx_debug;

	# USB
	echo "USB-Info:" >> /sdcard/dorimanx_debug;
	lsusb >> /sdcard/dorimanx_debug;
	echo "" >> /sdcard/dorimanx_debug;

	# Partitions 
	echo "Partitions-Info:" >> /sdcard/dorimanx_debug;
	mount >> /sdcard/dorimanx_debug;
	cat /proc/partitions >> /sdcard/dorimanx_debug;

	# Processes
	echo "Process-Info:" >> /sdcard/dorimanx_debug;
	top -n 1 >> /sdcard/dorimanx_debug;
	ps -wTl >> /sdcard/dorimanx_debug;
	echo "" >> /sdcard/dorimanx_debug;

	# Profile
	PROFILE=`cat /data/.siyah/.active.profile`;
	echo "Profile-Config: $PROFILE" >> /sdcard/dorimanx_debug;
	cat /data/.siyah/$PROFILE.profile >> /sdcard/dorimanx_debug;
	echo "" >> /sdcard/dorimanx_debug;

	# dmesg
	echo "dmesg-Info:" >> /sdcard/dorimanx_debug;
	dmesg >> /sdcard/dorimanx_debug;
	echo "" >> /sdcard/dorimanx_debug;

	# logcat
	echo "" > /sdcard/dorimanx_debug;
	logcat -f /sdcard/dorimanx_debug_logcat;
	# maybe we can also grep / remove personal infos here (e.g . email address)

	;;
	*)
	echo "need input";
	;;
esac;

