#!/sbin/busybox sh
export PATH="/res/customconfig/actions/push-actions:${PATH}";

if [ "a$2" == "a" ]; then
	echo $debug_to_sd;
else
	debug_to_sd=$2;
	echo $debug_to_sd;
fi;

case "${debug_to_sd}" in
	1)
	(
		SEPARATOR() {
			echo "" >> /sdcard/dorimanx_debug;
			echo " ---------------------------- " >> /sdcard/dorimanx_debug;
			echo "" >> /sdcard/dorimanx_debug;
		}
	
		# Kernel-Info
		echo "Kernel-Version:" > /sdcard/dorimanx_debug;
		cat /proc/version >> /sdcard/dorimanx_debug;
		SEPARATOR;

		date +"Last Reboot: %d.%m.%y / %H:%m" -d @$(( $(date +%s) - $(cut -f1 -d. /proc/uptime) )) >> /sdcard/dorimanx_debug;
		SEPARATOR;

		# System
		echo "ROM-Version:" >> /sdcard/dorimanx_debug;
		cat init.rc | grep "# THIS INIT.RC is FOR" >> /sdcard/dorimanx_debug;
		getprop ro.modversion >> /sdcard/dorimanx_debug;
		getprop cm.version >> /sdcard/dorimanx_debug;
		getprop ro.build.description >> /sdcard/dorimanx_debug;
		getprop ro.build.date >> /sdcard/dorimanx_debug;
		getprop ro.build.display.id >> /sdcard/dorimanx_debug;
		getprop ro.build.id >> /sdcard/dorimanx_debug;
		SEPARATOR;

		# Profile
		PROFILE=`cat /data/.siyah/.active.profile`;
		echo "Profile-Config: $PROFILE" >> /sdcard/dorimanx_debug;
		cat /data/.siyah/$PROFILE.profile >> /sdcard/dorimanx_debug;
		SEPARATOR;

		# Memory
		echo "Memory-Info:" >> /sdcard/dorimanx_debug;
		free >> /sdcard/dorimanx_debug;
		cat /proc/meminfo >> /sdcard/dorimanx_debug;
		SEPARATOR;

		# CPU
		echo "CPU-Info:" >> /sdcard/dorimanx_debug;
		scaling_governor=$(cat /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor)
		echo "CPU-Governor: $scaling_governor" >> /sdcard/dorimanx_debug;
		cpuinfo_cur_freq=$(cat /sys/devices/system/cpu/cpu0/cpufreq/cpuinfo_cur_freq);
		echo "Cur.-Freq: $cpuinfo_cur_freq" >> /sdcard/dorimanx_debug;
		scaling_max_freq=$(cat /sys/devices/system/cpu/cpu0/cpufreq/scaling_max_freq);
		echo "Max.-Freq: $scaling_max_freq" >> /sdcard/dorimanx_debug;
		scaling_min_freq=$(cat /sys/devices/system/cpu/cpu0/cpufreq/scaling_min_freq);
		echo "Min.-Freq: $scaling_min_freq" >> /sdcard/dorimanx_debug;
		total_trans=$(cat /sys/devices/system/cpu/cpu0/cpufreq/stats/total_trans);
		echo "Total freq-switch: $total_trans" >> /sdcard/dorimanx_debug;
		echo "" >> /sdcard/dorimanx_debug;
		echo "Time-In-State:" >> /sdcard/dorimanx_debug;
		cat /sys/devices/system/cpu/cpu0/cpufreq/stats/time_in_state >> /sdcard/dorimanx_debug;
		for i in `cat /sys/devices/system/cpu/cpu0/cpufreq/stats/time_in_state | cut -f 2 -d ' '`; do 
			summe=$(($summe+$i)); 
		done; 
		summe=$(($summe/100)); 
		summe=$(($summe/60)); 
		if [ $summe -lt 60 ]; then
			echo "uptime with CPU on: $summe min" >> /sdcard/dorimanx_debug;
		else
			summe=$(($summe/60)); 
			echo "uptime with CPU on: $summe h" >> /sdcard/dorimanx_debug;
		fi;
		echo "" >> /sdcard/dorimanx_debug;
		echo "Uptime:" >> /sdcard/dorimanx_debug;
		uptime >> /sdcard/dorimanx_debug;
		#cat /proc/loadavg >> /sdcard/dorimanx_debug;
		SEPARATOR;

		echo "more CPU-Infos:" >> /sdcard/dorimanx_debug;	
		cpuinfo_cur_freq=$(cat /sys/devices/system/cpu/cpu0/cpufreq/cpuinfo_cur_freq);
		for i in `ls /sys/devices/system/cpu/cpu0/cpufreq/`; do
			echo $i >> /sdcard/dorimanx_debug;
			cat /sys/devices/system/cpu/cpu0/cpufreq/$i >> /sdcard/dorimanx_debug 2>&1;
		done;
		SEPARATOR;

		# USB
		echo "USB-Info:" >> /sdcard/dorimanx_debug;
		lsusb >> /sdcard/dorimanx_debug;
		SEPARATOR;

		# lsmod
		echo "lsmod-Info:" >> /sdcard/dorimanx_debug;
		lsmod >> /sdcard/dorimanx_debug;
		SEPARATOR;

		# Partitions 
		echo "Partitions-Info:" >> /sdcard/dorimanx_debug;
		mount >> /sdcard/dorimanx_debug;
		cat /proc/partitions >> /sdcard/dorimanx_debug;
		SEPARATOR;

		# Processes
		echo "Process-Info:" >> /sdcard/dorimanx_debug;
		top -b -n 1 >> /sdcard/dorimanx_debug;
		ps -wTl >> /sdcard/dorimanx_debug;
		SEPARATOR;

		# dmesg
		echo "dmesg-Info:" >> /sdcard/dorimanx_debug;
		dmesg >> /sdcard/dorimanx_debug;
		SEPARATOR;
	)&
	echo "All Data collected and ready at /sdcard/dorimanx_debug";
	;;
	2)

	# logcat
	(
		logcat -f /sdcard/dorimanx_debug_logcat;
		wait 60;
		pkill logcat;
		#maybe we can also grep / remove personal infos here (e.g . email address)
	)&
	echo "Collecting logs for 60Sec please wait";
	;;	
	*)
	echo "need input";
	;;
esac;

