#!/sbin/busybox sh
(
/sbin/busybox echo /dev/block/vold/259:3 > /sys/devices/virtual/android_usb/android0/f_mass_storage/lun0/file

if [ -e /dev/block/vold/179:25 ]; then 
	/sbin/busybox echo /dev/block/vold/179:25 > /sys/devices/virtual/android_usb/android0/f_mass_storage/lun1/file
fi;
)&
/sbin/busybox echo Try now to open usb drive/s.

