#!/sbin/busybox sh

(
if [ `pgrep -f "fix_permissions" |  wc -l` \< 5 ]; then
	echo "Fixing permissions started! please leave the phone alone for 3min, no need to reboot.!";
	/sbin/fix_permissions > /dev/null 2>&1;
else
	echo "fix_permissions still running, please wait";
fi;
)&

