#!/sbin/busybox sh

mount -o remount,rw /system;

fixWifi="/system/run_fix_wifi";

if [ ! -e $fixWifi ]; then
	echo "fix wifi" > $fixWifi;
	echo "Activated! You have to reboot now!";
else
	rm -f $fixWifi;
	echo "ABORT, ABORT, ABORT :)";
fi;

