#!/sbin/busybox sh
export PATH="/res/customconfig/actions/push-actions:${PATH}";

case $1 in
	1)
		echo "Fixing permissions started! please wait 3MIN!";

		/sbin/fix_permissions;
        ;;
	*)
		echo "need input, 1=true"
		;;
esac;
