#!/sbin/busybox sh
export PATH="/res/customconfig/actions/push-actions:${PATH}";

if [ "a$1" == "a" ]; then
	echo $reset_fuelgauge;
else
	reset_fuelgauge=$1;
	echo $reset_fuelgauge;
fi;

case "${reset_fuelgauge}" in
	1)
		if [ ! -f /sys/devices/platform/i2c-gpio.9/i2c-9/9-0036/power_supply/fuelgauge/fg_reset_soc ]; then
			echo "The device file is not found. Fuel gauge chip cannot be reset."
			exit;
		else
			# In case user made reset Fuel Gauge Reset request.
			echo "1" > /sys/devices/platform/i2c-gpio.9/i2c-9/9-0036/power_supply/fuelgauge/fg_reset_soc;
			echo "The fuel gauge chip was reset. give it some time to normalize the gauge.";
		fi;
        ;;
	*)
		echo "need input, 1=true";
		;;
esac;
