#!/sbin/busybox sh

if [ ! -f /sys/devices/platform/i2c-gpio.9/i2c-9/9-0036/power_supply/fuelgauge/fg_reset_soc ]; then
	echo "The device file is not found. Fuel gauge chip cannot be reset."
else
	echo "fuel gauge reset" > /data/.siyah/fuel_gauge_reset
fi;

echo "The fuel gauge chip, will be reset on screen OFF one time only."
