#!/sbin/busybox sh

(
	BB=/sbin/busybox

	chmod 755 /sbin/read_boot_headers;
	eval $(/sbin/read_boot_headers /dev/block/mmcblk0p5);
	load_offset=$boot_offset;
	load_len=$boot_len;
	cd /;
	dd bs=512 if=/dev/block/mmcblk0p5 skip=$load_offset count=$load_len | xzcat | tar x;

	if [ -e /res/misc/payload/STweaks.apk ]; then
		rm -f /system/app/STweaks.apk > /dev/null 2>&1;
		rm -f /data/app/com.gokhanmoral.*weak*.apk > /dev/null 2>&1;
		rm -f /system/app/com.gokhanmoral.*weak*.apk > /dev/null 2>&1;
		rm -rf /data/data/com.gokhanmoral.*weak* > /dev/null 2>&1;
		rm -f /data/dalvik-cache/*gokhanmoral.*weak*.apk* > /dev/null 2>&1;
		rm -f /cache/dalvik-cache/*gokhanmoral.*weak*.apk* > /dev/null 2>&1;
		$BB cp -a /res/misc/payload/STweaks.apk /system/app/STweaks.apk;
		$BB chown 0.0 /system/app/STweaks.apk;
		$BB chmod 644 /system/app/STweaks.apk;
		pkill -f "com.gokhanmoral.stweaks.app";
		sleep 2
		am start -a android.intent.action.MAIN -n com.gokhanmoral.stweaks.app/.MainActivity;
	else
		echo "STweaks is missing or code error!";
	fi;

	rm -f /res/misc/payload/*;
)&

