#!/sbin/busybox sh

echo "Turn off the screen to test BLN.";

EXTWEAKSPUSH ()
{
    # Case if GM BLN active in kernel.
    if [ -e /sys/class/misc/notification/led ] && [ -e /data/.siyah/bln_test ]; then
        echo 1 > /sys/class/misc/notification/led;
        rm -f /data/.siyah/bln_test;
    fi;
    # Case if Myfluxi BLN active in kernel.
    if [ -e /sys/class/misc/backlightnotification/notification_led ] && [ -e /data/.siyah/bln_test ]; then
        echo 1 > /sys/class/misc/backlightnotification/notification_led;
        rm -f /data/.siyah/bln_test;
    fi;
    if [ -e /data/.siyah/fixperm ]; then
        /sbin/fix_permissions;
        rm -f /data/.siyah/fixperm;
    fi;
    # In case user made reset Fuel Gauge Reset request.
    if [ -e /data/.siyah/fuel_gauge_reset ]; then
        echo "1" > /sys/devices/platform/i2c-gpio.9/i2c-9/9-0036/power_supply/fuelgauge/fg_reset_soc;
        rm -f /data/.siyah/fuel_gauge_reset;
    fi;
}

echo "bln-test" > /data/.siyah/bln_test;
# waiting for screen-off, then ...
STATE=$(cat /sys/power/wait_for_fb_sleep);
EXTWEAKSPUSH;

