#!/sbin/busybox sh

PROFILE=`cat /data/.siyah/.active.profile`;
. /data/.siyah/$PROFILE.profile;

if [ "$zramtweaks" != 4 ]; then
	if [ -e /system/xbin/bash ] || [ -e /system/bin/bash ]; then
		/sbin/zram_stats_ex;
	else
		free;
	fi;
else
	echo "ZRAM IS OFFLINE";
fi;
