#!/sbin/busybox sh

sleep 60

DM=`ls -d /sys/block/dm*`;
for i in $DM

        if [ -e $i/queue/rotational ];
        then
                echo "0" > $i/queue/rotational;
        fi;

        if [ -e $i/queue/iostats ];
        then
                echo "0" > $i/queue/iostats;
        fi;

        if [ -e $i/queue/iosched/low_latency ];
        then
                echo "1" > $i/queue/iosched/low_latency;
        fi;

        if [ -e $i/queue/rq_affinity ];
        then
                echo "1" > $i/queue/rq_affinity;
        fi;

        if [ -e $i/queue/read_ahead_kb ];
        then
                echo "1024" >  $i/queue/read_ahead_kb;
        fi;
done;

for k in $(busybox mount | grep relatime | grep -v /acct | grep -v /dev/cpuctl | cut -d " " -f3);
do
        busybox mount -o remount,noatime,nodiratime $k;
done;

mount -o remount,rw /system

exit 1

